% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
%
\documentclass[
]{article}
\usepackage{amsmath,amssymb}
\usepackage{lmodern}
\usepackage{ifxetex,ifluatex}
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math}
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{xcolor}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\IfFileExists{bookmark.sty}{\usepackage{bookmark}}{\usepackage{hyperref}}
\hypersetup{
  pdftitle={Lab 3},
  pdfauthor={Elizabeth McHugh},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}
\urlstyle{same} % disable monospaced font for URLs
\usepackage[margin=1in]{geometry}
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.77,0.63,0.00}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{longtable,booktabs,array}
\usepackage{calc} % for calculating minipage widths
% Correct order of tables after \paragraph or \subparagraph
\usepackage{etoolbox}
\makeatletter
\patchcmd\longtable{\par}{\if@noskipsec\mbox{}\fi\par}{}{}
\makeatother
% Allow footnotes in longtable head/foot
\IfFileExists{footnotehyper.sty}{\usepackage{footnotehyper}}{\usepackage{footnote}}
\makesavenoteenv{longtable}
\usepackage{graphicx}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
% Set default figure placement to htbp
\makeatletter
\def\fps@figure{htbp}
\makeatother
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\ifluatex
  \usepackage{selnolig}  % disable illegal ligatures
\fi

\title{Lab 3}
\author{Elizabeth McHugh}
\date{11:59PM March 4, 2021}

\begin{document}
\maketitle

\hypertarget{support-vector-machine-vs.-perceptron}{%
\subsection{Support Vector Machine
vs.~Perceptron}\label{support-vector-machine-vs.-perceptron}}

We recreate the data from the previous lab and visualize it:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(ggplot2)}
\NormalTok{Xy\_simple }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}
 \AttributeTok{response =} \FunctionTok{factor}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{)), }\CommentTok{\#nominal}
 \AttributeTok{first\_feature =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{),    }\CommentTok{\#continuous}
 \AttributeTok{second\_feature =} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{3}\NormalTok{)    }\CommentTok{\#continuous}
\NormalTok{)}
\NormalTok{simple\_viz\_obj }\OtherTok{=} \FunctionTok{ggplot}\NormalTok{(Xy\_simple, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ first\_feature, }\AttributeTok{y =}\NormalTok{ second\_feature, }\AttributeTok{color =}\NormalTok{ response)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{5}\NormalTok{)}
\NormalTok{simple\_viz\_obj}
\end{Highlighting}
\end{Shaded}

\includegraphics{lab3_files/figure-latex/unnamed-chunk-2-1.pdf}

Use the \texttt{e1071} package to fit an SVM model to the simple data.
Use a formula to create the model, pass in the data frame, set kernel to
be \texttt{linear} for the linear SVM and don't scale the covariates.
Call the model object \texttt{svm\_model}. Otherwise the remaining code
won't work.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(e1071)}

\NormalTok{Xy\_simple\_feature\_matrix }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(Xy\_simple[, }\DecValTok{2} \SpecialCharTok{:} \DecValTok{3}\NormalTok{])}
\CommentTok{\# n = nrow(Xy\_simple\_feature\_matrix)}

\NormalTok{svm\_model }\OtherTok{=} \FunctionTok{svm}\NormalTok{(}
\NormalTok{  Xy\_simple\_feature\_matrix, }
  \AttributeTok{data =}\NormalTok{ Xy\_simple}\SpecialCharTok{$}\NormalTok{response, }
  \AttributeTok{kernel =} \StringTok{"linear"}\NormalTok{, }
  \AttributeTok{scale =} \ConstantTok{FALSE}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

and then use the following code to visualize the line in purple:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{w\_vec\_simple\_svm }\OtherTok{=} \FunctionTok{c}\NormalTok{(}
\NormalTok{  svm\_model}\SpecialCharTok{$}\NormalTok{rho, }\CommentTok{\#the b term}
  \SpecialCharTok{{-}}\FunctionTok{t}\NormalTok{(svm\_model}\SpecialCharTok{$}\NormalTok{coefs) }\SpecialCharTok{\%*\%} \FunctionTok{cbind}\NormalTok{(Xy\_simple}\SpecialCharTok{$}\NormalTok{first\_feature, Xy\_simple}\SpecialCharTok{$}\NormalTok{second\_feature)[svm\_model}\SpecialCharTok{$}\NormalTok{index, ] }\CommentTok{\# the other terms}
\NormalTok{)}
\NormalTok{simple\_svm\_line }\OtherTok{=} \FunctionTok{geom\_abline}\NormalTok{(}
    \AttributeTok{intercept =} \SpecialCharTok{{-}}\NormalTok{w\_vec\_simple\_svm[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ w\_vec\_simple\_svm[}\DecValTok{3}\NormalTok{], }
    \AttributeTok{slope =} \SpecialCharTok{{-}}\NormalTok{w\_vec\_simple\_svm[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ w\_vec\_simple\_svm[}\DecValTok{3}\NormalTok{], }
    \AttributeTok{color =} \StringTok{"purple"}\NormalTok{)}
\NormalTok{simple\_viz\_obj }\SpecialCharTok{+}\NormalTok{ simple\_svm\_line}
\end{Highlighting}
\end{Shaded}

\includegraphics{lab3_files/figure-latex/unnamed-chunk-4-1.pdf}

Source the \texttt{perceptron\_learning\_algorithm} function from lab 2.
Then run the following to fit the perceptron and plot its line in orange
with the SVM's line:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{perceptron\_learning\_algorithm }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(Xinput, y\_binary, }\AttributeTok{MAX\_ITER =} \DecValTok{1000}\NormalTok{, }\AttributeTok{w =} \FunctionTok{rep}\NormalTok{(}\DecValTok{0}\NormalTok{, (}\FunctionTok{ncol}\NormalTok{(Xinput) }\SpecialCharTok{+} \DecValTok{1}\NormalTok{)))\{}
 
\NormalTok{  X }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\DecValTok{1}\NormalTok{, Xinput[, , }\AttributeTok{drop =} \ConstantTok{FALSE}\NormalTok{]))}
    
    \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\NormalTok{ MAX\_ITER)\{}
      
      \ControlFlowTok{for}\NormalTok{(j }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:} \FunctionTok{nrow}\NormalTok{(X))\{}
\NormalTok{        x\_j }\OtherTok{=}\NormalTok{ X[j,]}
\NormalTok{        yhat\_j }\OtherTok{=} \FunctionTok{ifelse}\NormalTok{(}\FunctionTok{sum}\NormalTok{(x\_j }\SpecialCharTok{*}\NormalTok{ w) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{, }\DecValTok{1}\NormalTok{, }\DecValTok{0}\NormalTok{)}
\NormalTok{        y\_j }\OtherTok{=}\NormalTok{ y\_binary[j]}
        
        \ControlFlowTok{for}\NormalTok{ (k }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:} \FunctionTok{ncol}\NormalTok{(X))\{}
\NormalTok{          w[k] }\OtherTok{=}\NormalTok{ w[k] }\SpecialCharTok{+}\NormalTok{ (y\_j }\SpecialCharTok{{-}}\NormalTok{ yhat\_j) }\SpecialCharTok{*}\NormalTok{ x\_j[k]}
\NormalTok{        \}}
\NormalTok{      \} }
\NormalTok{    \}}
\NormalTok{   w}
\NormalTok{\}}

\NormalTok{w\_vec\_simple\_per }\OtherTok{=} \FunctionTok{perceptron\_learning\_algorithm}\NormalTok{(}
  \FunctionTok{cbind}\NormalTok{(Xy\_simple}\SpecialCharTok{$}\NormalTok{first\_feature, Xy\_simple}\SpecialCharTok{$}\NormalTok{second\_feature),}
  \FunctionTok{as.numeric}\NormalTok{(Xy\_simple}\SpecialCharTok{$}\NormalTok{response }\SpecialCharTok{==} \DecValTok{1}\NormalTok{)}
\NormalTok{)}
\NormalTok{simple\_perceptron\_line }\OtherTok{=} \FunctionTok{geom\_abline}\NormalTok{(}
    \AttributeTok{intercept =} \SpecialCharTok{{-}}\NormalTok{w\_vec\_simple\_per[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ w\_vec\_simple\_per[}\DecValTok{3}\NormalTok{], }
    \AttributeTok{slope =} \SpecialCharTok{{-}}\NormalTok{w\_vec\_simple\_per[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ w\_vec\_simple\_per[}\DecValTok{3}\NormalTok{], }
    \AttributeTok{color =} \StringTok{"orange"}\NormalTok{)}
\NormalTok{simple\_viz\_obj }\SpecialCharTok{+}\NormalTok{ simple\_perceptron\_line }\SpecialCharTok{+}\NormalTok{ simple\_svm\_line}
\end{Highlighting}
\end{Shaded}

\includegraphics{lab3_files/figure-latex/unnamed-chunk-5-1.pdf}

Is this SVM line a better fit than the perceptron?

Without any more data, this SVM line is a much better fit than the
perceptron from lab \#2, as it seems to more adequately split the data
in half with a more equal buffer around each category for predicting
future outcomes.

Now write pseuocode for your own implementation of the linear support
vector machine algorithm using the Vapnik objective function we
discussed.

Note there are differences between this spec and the perceptron learning
algorithm spec in question \#1. You should figure out a way to respect
the \texttt{MAX\_ITER} argument value.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#\textquotesingle{} Support Vector Machine }
\CommentTok{\#}
\CommentTok{\#\textquotesingle{} This function implements the hinge{-}loss + maximum margin linear support vector machine algorithm of Vladimir Vapnik (1963).}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#\textquotesingle{} @param Xinput      The training data features as an n x p matrix.}
\CommentTok{\#\textquotesingle{} @param y\_binary    The training data responses as a vector of length n consisting of only 0\textquotesingle{}s and 1\textquotesingle{}s.}
\CommentTok{\#\textquotesingle{} @param MAX\_ITER    The maximum number of iterations the algorithm performs. Defaults to 5000.}
\CommentTok{\#\textquotesingle{} @param lambda      A scalar hyperparameter trading off margin of the hyperplane versus average hinge loss.}
\CommentTok{\#\textquotesingle{}                    The default value is 1.}
\CommentTok{\#\textquotesingle{} @return            The computed final parameter (weight) as a vector of length p + 1}
\NormalTok{linear\_svm\_learning\_algorithm }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(Xinput, y\_binary, }\AttributeTok{MAX\_ITER =} \DecValTok{5000}\NormalTok{, }\AttributeTok{lambda =} \FloatTok{0.1}\NormalTok{)\{}
  \CommentTok{\#TO{-}DO: write pseudo code in comments}
  
  
  \CommentTok{\#initialize n and p}
  
  \CommentTok{\#define SHE}
  
  \CommentTok{\#for loop to test for min w}
      \CommentTok{\#find w such that (1/n)SHE + lambda * norm\_squared(w) is minimized}
  
  \CommentTok{\#output w}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

If you are enrolled in 342W the following is extra credit but if you're
enrolled in 650, the following is required. Write the actual code. You
may want to take a look at the \texttt{optimx} package. You can feel
free to define another function (a ``private'' function) in this chunk
if you wish. R has a way to create public and private functions, but I
believe you need to create a package to do that (beyond the scope of
this course).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#\textquotesingle{} This function implements the hinge{-}loss + maximum margin linear support vector machine algorithm of Vladimir Vapnik (1963).}
\CommentTok{\#\textquotesingle{}}
\CommentTok{\#\textquotesingle{} @param Xinput      The training data features as an n x p matrix.}
\CommentTok{\#\textquotesingle{} @param y\_binary    The training data responses as a vector of length n consisting of only 0\textquotesingle{}s and 1\textquotesingle{}s.}
\CommentTok{\#\textquotesingle{} @param MAX\_ITER    The maximum number of iterations the algorithm performs. Defaults to 5000.}
\CommentTok{\#\textquotesingle{} @param lambda      A scalar hyperparameter trading off margin of the hyperplane versus average hinge loss.}
\CommentTok{\#\textquotesingle{}                    The default value is 1.0}
\CommentTok{\#\textquotesingle{} @return            The computed final parameter (weight) as a vector of length p + 1}
\NormalTok{linear\_svm\_learning\_algorithm }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(Xinput, y\_binary, }\AttributeTok{MAX\_ITER =} \DecValTok{5000}\NormalTok{, }\AttributeTok{lambda =} \FloatTok{0.1}\NormalTok{)\{}
  \CommentTok{\#TO{-}DO}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

If you wrote code (the extra credit), run your function using the
defaults and plot it in brown vis-a-vis the previous model's line:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{svm\_model\_weights }\OtherTok{=} \FunctionTok{linear\_svm\_learning\_algorithm}\NormalTok{(X\_simple\_feature\_matrix, y\_binary)}
\NormalTok{my\_svm\_line }\OtherTok{=} \FunctionTok{geom\_abline}\NormalTok{(}
    \AttributeTok{intercept =}\NormalTok{ svm\_model\_weights[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ svm\_model\_weights[}\DecValTok{3}\NormalTok{],}\CommentTok{\#NOTE: negative sign removed from intercept argument here}
    \AttributeTok{slope =} \SpecialCharTok{{-}}\NormalTok{svm\_model\_weights[}\DecValTok{2}\NormalTok{] }\SpecialCharTok{/}\NormalTok{ svm\_model\_weights[}\DecValTok{3}\NormalTok{], }
    \AttributeTok{color =} \StringTok{"brown"}\NormalTok{)}
\NormalTok{simple\_viz\_obj  }\SpecialCharTok{+}\NormalTok{ my\_svm\_line}
\end{Highlighting}
\end{Shaded}

Is this the same as what the \texttt{e1071} implementation returned? Why
or why not?

TO-DO

We now move on to simple linear modeling using the ordinary least
squares algorithm.

Let's quickly recreate the sample data set from practice lecture 7:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{n }\OtherTok{=} \DecValTok{20}
\NormalTok{x }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n)}
\NormalTok{beta\_0 }\OtherTok{=} \DecValTok{3}
\NormalTok{beta\_1 }\OtherTok{=} \SpecialCharTok{{-}}\DecValTok{2}
\end{Highlighting}
\end{Shaded}

Compute \(h^*(x)\) as
\texttt{h\_star\_x,\ then\ draw\ \$\textbackslash{}epsilon\ \textbackslash{}sim\ N(0,\ 0.33\^{}2)\$\ as}epsilon`,
then compute \(\y\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{h\_star\_x }\OtherTok{=}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x}
\NormalTok{epsilon }\OtherTok{=} \FunctionTok{rnorm}\NormalTok{(n, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \FloatTok{0.33}\NormalTok{)}
\NormalTok{y }\OtherTok{=}\NormalTok{ h\_star\_x}
\end{Highlighting}
\end{Shaded}

Graph the data by running the following chunk:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(ggplot2)}
\NormalTok{simple\_df }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{y =}\NormalTok{ y)}
\NormalTok{simple\_viz\_obj }\OtherTok{=} \FunctionTok{ggplot}\NormalTok{(simple\_df, }\FunctionTok{aes}\NormalTok{(x, y)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{size =} \DecValTok{2}\NormalTok{)}
\NormalTok{simple\_viz\_obj}
\end{Highlighting}
\end{Shaded}

\includegraphics{lab3_files/figure-latex/unnamed-chunk-11-1.pdf}

Does this make sense given the values of \(beta_0\) and \(beta_1\)?

This does make sense, based on the given intercept of 3 and slope of -2.
\#FINISH ME

Write a function \texttt{my\_simple\_ols} that takes in a vector
\texttt{x} and vector \texttt{y} and returns a list that contains the
\texttt{b\_0} (intercept), \texttt{b\_1} (slope), \texttt{yhat} (the
predictions), \texttt{e} (the residuals), \texttt{SSE}, \texttt{SST},
\texttt{MSE}, \texttt{RMSE} and \texttt{Rsq} (for the R-squared metric).
Internally, you can only use the functions \texttt{sum} and
\texttt{length} and other basic arithmetic operations. You should throw
errors if the inputs are non-numeric or not the same length. You should
also name the class of the return value \texttt{my\_simple\_ols\_obj} by
using the \texttt{class} function as a setter. No need to create ROxygen
documentation here.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my\_simple\_ols }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x, y)\{}

\NormalTok{n }\OtherTok{=} \FunctionTok{length}\NormalTok{(y)}

\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(x) }\SpecialCharTok{!=}\NormalTok{ n)\{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"x and y must be the same length"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{class}\NormalTok{(x) }\SpecialCharTok{!=} \StringTok{"numeric"} \SpecialCharTok{\&\&} \FunctionTok{class}\NormalTok{(x) }\SpecialCharTok{!=} \StringTok{"integer"}\NormalTok{)\{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"x must be numeric or integer"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{class}\NormalTok{(y) }\SpecialCharTok{!=} \StringTok{"numeric"} \SpecialCharTok{\&\&} \FunctionTok{class}\NormalTok{(y) }\SpecialCharTok{!=} \StringTok{"integer"}\NormalTok{)\{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"y must be numeric or integer"}\NormalTok{)}
\NormalTok{\}}
\ControlFlowTok{if}\NormalTok{ (n }\SpecialCharTok{\textless{}=} \DecValTok{2}\NormalTok{)  \{}
  \FunctionTok{stop}\NormalTok{(}\StringTok{"n must be greater than 2"}\NormalTok{)}
\NormalTok{\}}

\NormalTok{x\_bar }\OtherTok{=} \FunctionTok{sum}\NormalTok{(x)}\SpecialCharTok{/}\NormalTok{n}
\NormalTok{y\_bar }\OtherTok{=} \FunctionTok{sum}\NormalTok{(y)}\SpecialCharTok{/}\NormalTok{n}

\NormalTok{b\_1 }\OtherTok{=}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(x}\SpecialCharTok{*}\NormalTok{y) }\SpecialCharTok{{-}}\NormalTok{ n }\SpecialCharTok{*}\NormalTok{ x\_bar }\SpecialCharTok{*}\NormalTok{ y\_bar) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{sum}\NormalTok{(x}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{{-}}\NormalTok{ n }\SpecialCharTok{*}\NormalTok{ (x\_bar)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{b\_0 }\OtherTok{=}\NormalTok{ y\_bar }\SpecialCharTok{{-}}\NormalTok{ b\_1 }\SpecialCharTok{*}\NormalTok{ x\_bar}

\NormalTok{y\_hat }\OtherTok{=}\NormalTok{ b\_0 }\SpecialCharTok{+}\NormalTok{ b\_1 }\SpecialCharTok{*}\NormalTok{ x}
\NormalTok{e }\OtherTok{=}\NormalTok{ y }\SpecialCharTok{{-}}\NormalTok{ y\_hat}
\NormalTok{SSE }\OtherTok{=} \FunctionTok{sum}\NormalTok{(e}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{SST }\OtherTok{=} \FunctionTok{sum}\NormalTok{( (y }\SpecialCharTok{{-}}\NormalTok{ y\_bar)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{MSE }\OtherTok{=}\NormalTok{ SSE }\SpecialCharTok{/}\NormalTok{ (n }\SpecialCharTok{{-}} \DecValTok{2}\NormalTok{)}
\NormalTok{RMSE }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(MSE)}
\NormalTok{R\_squared }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ SSE }\SpecialCharTok{/}\NormalTok{ SST}

\NormalTok{model }\OtherTok{=} \FunctionTok{list}\NormalTok{(}\AttributeTok{b\_0 =}\NormalTok{ b\_0, }\AttributeTok{b\_1 =}\NormalTok{ b\_1, }\AttributeTok{y\_hat =}\NormalTok{ y\_hat, }\AttributeTok{e =}\NormalTok{ e, }\AttributeTok{SSE =}\NormalTok{ SSE, }\AttributeTok{SST =}\NormalTok{ SST, }\AttributeTok{MSE =}\NormalTok{ MSE, }\AttributeTok{RMSE =}\NormalTok{ RMSE, }\AttributeTok{R\_squared =}\NormalTok{ R\_squared)}
\FunctionTok{class}\NormalTok{(model) }\OtherTok{=} \StringTok{"my\_simple\_ols\_obj"}
\NormalTok{model}

\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Verify your computations are correct for the vectors \texttt{x} and
\texttt{y} from the first chunk using the \texttt{lm} function in R:

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{lm\_mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}
\NormalTok{my\_simple\_ols\_mod }\OtherTok{=} \FunctionTok{my\_simple\_ols}\NormalTok{(x, y)}
\CommentTok{\#run the tests to ensure the function is up to spec}
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(testthat)}
\FunctionTok{expect\_equal}\NormalTok{(my\_simple\_ols\_mod}\SpecialCharTok{$}\NormalTok{b\_0, }\FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{coef}\NormalTok{(lm\_mod)[}\DecValTok{1}\NormalTok{]), }\AttributeTok{tol =} \FloatTok{1e{-}4}\NormalTok{)}
\FunctionTok{expect\_equal}\NormalTok{(my\_simple\_ols\_mod}\SpecialCharTok{$}\NormalTok{b\_1, }\FunctionTok{as.numeric}\NormalTok{(}\FunctionTok{coef}\NormalTok{(lm\_mod)[}\DecValTok{2}\NormalTok{]), }\AttributeTok{tol =} \FloatTok{1e{-}4}\NormalTok{)}
\FunctionTok{expect\_equal}\NormalTok{(my\_simple\_ols\_mod}\SpecialCharTok{$}\NormalTok{RMSE, }\FunctionTok{summary}\NormalTok{(lm\_mod)}\SpecialCharTok{$}\NormalTok{sigma, }\AttributeTok{tol =} \FloatTok{1e{-}4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in summary.lm(lm_mod): essentially perfect fit: summary may be
## unreliable
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{expect\_equal}\NormalTok{(my\_simple\_ols\_mod}\SpecialCharTok{$}\NormalTok{Rsq, }\FunctionTok{summary}\NormalTok{(lm\_mod)}\SpecialCharTok{$}\NormalTok{R\_squared, }\AttributeTok{tol =} \FloatTok{1e{-}4}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning in summary.lm(lm_mod): essentially perfect fit: summary may be
## unreliable
\end{verbatim}

Verify that the average of the residuals is 0 using the
\texttt{expect\_equal}. Hint: use the syntax above.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{expect\_equal}\NormalTok{(}\FunctionTok{mean}\NormalTok{(my\_simple\_ols\_mod}\SpecialCharTok{$}\NormalTok{e), }\DecValTok{0}\NormalTok{, }\AttributeTok{tol =} \FloatTok{1e{-}4}\NormalTok{ ) }
\end{Highlighting}
\end{Shaded}

Create the \(X\) matrix for this data example. Make sure it has the
correct dimension.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\DecValTok{1}\NormalTok{,x)}
\FunctionTok{dim}\NormalTok{(X)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 20  2
\end{verbatim}

Use the \texttt{model.matrix} function to compute the matrix \texttt{X}
and verify it is the same as your manual construction.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{model.matrix}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{x)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    (Intercept)           x
## 1            1 0.214506738
## 2            1 0.447130195
## 3            1 0.586524019
## 4            1 0.664827225
## 5            1 0.845769949
## 6            1 0.760624549
## 7            1 0.696839952
## 8            1 0.340433524
## 9            1 0.002945276
## 10           1 0.055585564
## 11           1 0.223021122
## 12           1 0.979745496
## 13           1 0.788445341
## 14           1 0.037807847
## 15           1 0.573426774
## 16           1 0.988367794
## 17           1 0.203953294
## 18           1 0.810408280
## 19           1 0.480516035
## 20           1 0.978150041
## attr(,"assign")
## [1] 0 1
\end{verbatim}

Create a prediction method \texttt{g} that takes in a vector
\texttt{x\_star} and \texttt{my\_simple\_ols\_obj}, an object of type
\texttt{my\_simple\_ols\_obj} and predicts y values for each entry in
\texttt{x\_star}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{g }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(my\_simple\_ols\_obj, x\_star)\{}
\NormalTok{  my\_simple\_ols\_obj}\SpecialCharTok{$}\NormalTok{b\_0 }\SpecialCharTok{+}\NormalTok{ my\_simple\_ols\_obj}\SpecialCharTok{$}\NormalTok{b\_1 }\SpecialCharTok{*}\NormalTok{ x\_star}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Use this function to verify that when predicting for the average x, you
get the average y.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{expect\_equal}\NormalTok{(}\FunctionTok{g}\NormalTok{(my\_simple\_ols\_mod, }\FunctionTok{mean}\NormalTok{(x)), }\FunctionTok{mean}\NormalTok{(y))}
\end{Highlighting}
\end{Shaded}

In class we spoke about error due to ignorance, misspecification error
and estimation error. Show that as n grows, estimation error shrinks.
Let us define an error metric that is the difference between \(b_0\) and
\(b_1\) and \(\beta_0\) and \(\beta_1\). How about
\(h = ||b - \beta||^2\) where the quantities are now the vectors of size
two. Show as n increases, this shrinks.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{beta\_0 }\OtherTok{=} \DecValTok{3}
\NormalTok{beta\_1 }\OtherTok{=} \SpecialCharTok{{-}}\DecValTok{2}
\NormalTok{beta }\OtherTok{=} \FunctionTok{c}\NormalTok{(beta\_0, beta\_1)        }\CommentTok{\#vector to hold errors}
\NormalTok{ns }\OtherTok{=} \DecValTok{10}\SpecialCharTok{\^{}}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{6}\NormalTok{)}
\NormalTok{error\_in\_b }\OtherTok{=} \FunctionTok{array}\NormalTok{(}\ConstantTok{NA}\NormalTok{, }\FunctionTok{length}\NormalTok{(ns))}
\ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \DecValTok{1} \SpecialCharTok{:} \FunctionTok{length}\NormalTok{(ns)) \{}
\NormalTok{  n }\OtherTok{=}\NormalTok{ ns[i]}
\NormalTok{  x }\OtherTok{=} \FunctionTok{runif}\NormalTok{(n)}
\NormalTok{  h\_star\_x }\OtherTok{=}\NormalTok{ beta\_0 }\SpecialCharTok{+}\NormalTok{ beta\_1 }\SpecialCharTok{*}\NormalTok{ x }
\NormalTok{  epsilon }\OtherTok{=} \FunctionTok{rnorm}\NormalTok{(n, }\AttributeTok{mean =} \DecValTok{0}\NormalTok{, }\AttributeTok{sd =} \FloatTok{0.33}\NormalTok{)}
\NormalTok{  y }\OtherTok{=}\NormalTok{ h\_star\_x }\SpecialCharTok{+}\NormalTok{ epsilon}
  
\NormalTok{  mod }\OtherTok{=} \FunctionTok{my\_simple\_ols}\NormalTok{(x,y)}
  
\NormalTok{  b }\OtherTok{=} \FunctionTok{c}\NormalTok{(mod}\SpecialCharTok{$}\NormalTok{b\_0, mod}\SpecialCharTok{$}\NormalTok{b\_1)}
  
\NormalTok{  error\_in\_b[i] }\OtherTok{=} \FunctionTok{sum}\NormalTok{((beta }\SpecialCharTok{{-}}\NormalTok{ b)}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{)}
\NormalTok{\}}

\NormalTok{error\_in\_b}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4.087649e-01 3.786804e-02 5.595176e-04 2.233801e-05 4.131432e-05
## [6] 7.219635e-08
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{log}\NormalTok{(error\_in\_b, }\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] -0.3885264 -1.4217272 -3.2521862 -4.6509554 -4.3838994 -7.1414848
\end{verbatim}

We are now going to repeat one of the first linear model building
exercises in history --- that of Sir Francis Galton in 1886. First load
up package \texttt{HistData}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(HistData)}
\end{Highlighting}
\end{Shaded}

In it, there is a dataset called \texttt{Galton}. Load it up.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{data}\NormalTok{(Galton)}
\end{Highlighting}
\end{Shaded}

You now should have a data frame in your workspace called
\texttt{Galton}. Summarize this data frame and write a few sentences
about what you see. Make sure you report \(n\), \(p\) and a bit about
what the columns represent and how the data was measured. See the help
file \texttt{?Galton}. p is 1 and n is 928 the number of observations

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(skimr)}
\FunctionTok{skim}\NormalTok{(Galton)}
\end{Highlighting}
\end{Shaded}

\begin{longtable}[]{@{}ll@{}}
\caption{Data summary}\tabularnewline
\toprule
& \\
\midrule
\endfirsthead
\toprule
& \\
\midrule
\endhead
Name & Galton \\
Number of rows & 928 \\
Number of columns & 2 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Column type frequency: & \\
numeric & 2 \\
\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_\_ & \\
Group variables & None \\
\bottomrule
\end{longtable}

\textbf{Variable type: numeric}

\begin{longtable}[]{@{}lrrrrrrrrrl@{}}
\toprule
skim\_variable & n\_missing & complete\_rate & mean & sd & p0 & p25 &
p50 & p75 & p100 & hist \\
\midrule
\endhead
parent & 0 & 1 & 68.31 & 1.79 & 64.0 & 67.5 & 68.5 & 69.5 & 73.0 &
▃▇▆▇▂ \\
child & 0 & 1 & 68.09 & 2.52 & 61.7 & 66.2 & 68.2 & 70.2 & 73.7 &
▁▆▆▇▂ \\
\bottomrule
\end{longtable}

TO-DO

Find the average height (include both parents and children in this
computation).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{avg\_height }\OtherTok{=} \FunctionTok{mean}\NormalTok{(}\FunctionTok{c}\NormalTok{(Galton}\SpecialCharTok{$}\NormalTok{parent, Galton}\SpecialCharTok{$}\NormalTok{child))}
\NormalTok{avg\_height}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 68.19833
\end{verbatim}

If you were predicting child height from parent height and you were
using the null model, what would the RMSE of the null model be?

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{sqrt}\NormalTok{(}\FunctionTok{sum}\NormalTok{((Galton}\SpecialCharTok{$}\NormalTok{child }\SpecialCharTok{{-}} \FunctionTok{mean}\NormalTok{(Galton}\SpecialCharTok{$}\NormalTok{child))}\SpecialCharTok{\^{}}\DecValTok{2}\NormalTok{) }\SpecialCharTok{/}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(Galton)}\SpecialCharTok{{-}}\DecValTok{1}\NormalTok{))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.517941
\end{verbatim}

Note that in Math 241 you learned that the sample average is an estimate
of the ``mean'', the population expected value of height. We will call
the average the ``mean'' going forward since it is probably correct to
the nearest tenth of an inch with this amount of data.

Run a linear model attempting to explain the childrens' height using the
parents' height. Use \texttt{lm} and use the R formula notation. Compute
and report \(b_0\), \(b_1\), RMSE and \(R^2\).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(child }\SpecialCharTok{\textasciitilde{}}\NormalTok{ parent, Galton)}

\NormalTok{b\_0 }\OtherTok{=} \FunctionTok{coef}\NormalTok{(mod)[}\DecValTok{1}\NormalTok{]}
\NormalTok{b\_1 }\OtherTok{=} \FunctionTok{coef}\NormalTok{(mod)[}\DecValTok{2}\NormalTok{]}
  
\NormalTok{RMSE }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{sigma}

\NormalTok{r\_squared }\OtherTok{=} \FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{r.squared}

\NormalTok{mod}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = child ~ parent, data = Galton)
## 
## Coefficients:
## (Intercept)       parent  
##     23.9415       0.6463
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{RMSE}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 2.238547
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{r\_squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.2104629
\end{verbatim}

Interpret all four quantities: \(b_0\), \(b_1\), RMSE and \(R^2\). Use
the correct units of these metrics in your answer.

b\_0 is the ``intercept'' term, which gives us that if a parent is 0
tainll, the child is predicted to be 23.9415 in tall, and the b\_1 term
gives us that for each centimeter tall the parent is, the child is
predicted to be 0.6463 in taller than 23.9415in. For example, for a
parent who is 60 in tall, the child will be predicted to be 23.9415in +
60 * 0.6463in (or 62.7194 in) tall. The RMSE of mod gives us that the
model is off by 2.248547 centimeters on average (within the training
data range). The R\^{}2 of 0.2104629 is quite low, which shows us that
this might not be the best model for predicting height of children from
the height of a parent.

How good is this model? How well does it predict? Discuss.

The model predicts. (It is, after all, a predictive model.) However,
with a low R\^{}2 error, the model might not be expected to be ``good'',
even though the RMSE of just over 2 centimeters seems be an okay error
for prediction. Considering both R\^{}2 and RMSE, I'm not sure I would
be too thrilled with using this model to predict the height of my
children with much accuracy.

It is reasonable to assume that parents and their children have the same
height? Explain why this is reasonable using basic biology and common
sense.

Since it is known that genetics influence height, it would be reasonable
to assume that children have approximately the same heights of their
parents, though each parent likely has a different height.

If they were to have the same height and any differences were just
random noise with expectation 0, what would the values of \(\beta_0\)
and \(\beta_1\) be?

The value of beta\_0 would be 0, and the value of beta\_1 would be
approximately 1, leaving the predicted height about equal to that of the
parent.

Let's plot (a) the data in \(\mathbb{D}\) as black dots, (b) your least
squares line defined by \(b_0\) and \(b_1\) in blue, (c) the theoretical
line \(\beta_0\) and \(\beta_1\) if the parent-child height equality
held in red and (d) the mean height in green.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pacman}\SpecialCharTok{::}\FunctionTok{p\_load}\NormalTok{(ggplot2)}
\FunctionTok{ggplot}\NormalTok{(Galton, }\FunctionTok{aes}\NormalTok{(}\AttributeTok{x =}\NormalTok{ parent, }\AttributeTok{y =}\NormalTok{ child)) }\SpecialCharTok{+} 
  \FunctionTok{geom\_point}\NormalTok{() }\SpecialCharTok{+} 
  \FunctionTok{geom\_jitter}\NormalTok{() }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =}\NormalTok{ b\_0, }\AttributeTok{slope =}\NormalTok{ b\_1, }\AttributeTok{color =} \StringTok{"blue"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =} \DecValTok{0}\NormalTok{, }\AttributeTok{slope =} \DecValTok{1}\NormalTok{, }\AttributeTok{color =} \StringTok{"red"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{geom\_abline}\NormalTok{(}\AttributeTok{intercept =}\NormalTok{ avg\_height, }\AttributeTok{slope =} \DecValTok{0}\NormalTok{, }\AttributeTok{color =} \StringTok{"darkgreen"}\NormalTok{, }\AttributeTok{size =} \DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{xlim}\NormalTok{(}\FloatTok{63.5}\NormalTok{, }\FloatTok{72.5}\NormalTok{) }\SpecialCharTok{+} 
  \FunctionTok{ylim}\NormalTok{(}\FloatTok{63.5}\NormalTok{, }\FloatTok{72.5}\NormalTok{) }\SpecialCharTok{+}
  \FunctionTok{coord\_equal}\NormalTok{(}\AttributeTok{ratio =} \DecValTok{1}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Warning: Removed 76 rows containing missing values (geom_point).
\end{verbatim}

\begin{verbatim}
## Warning: Removed 86 rows containing missing values (geom_point).
\end{verbatim}

\includegraphics{lab3_files/figure-latex/unnamed-chunk-26-1.pdf}

Fill in the following sentence:

Children of short parents became taller on average and children of tall
parents became shorter on average.

Why did Galton call it ``Regression towards mediocrity in hereditary
stature'' which was later shortened to ``regression to the mean''?

As time moved on, the exceptionalities within height (shortness or
tallness) were ``neutralized'', so to speak, bringing both ends of the
spectrum closer to the ``average'' height.

Why should this effect be real?

This effect should be real because nature likes balance.

You now have unlocked the mystery. Why is it that when modeling with
\(y\) continuous, everyone calls it ``regression''? Write a better, more
descriptive and appropriate name for building predictive models with
\(y\) continuous.

When modeling with y continuous, the model ``draws'' predictions towards
the mean of the model. A more descriptive and appropriate name for
building predictive models with y continuous might be ``building a model
to predict future values around the linear mean of known data''.
However, that would be a horrible name for a modeling process.

You can now clear the workspace. Create a dataset \(\mathbb{D}\) which
we call \texttt{Xy} such that the linear model as \(R^2\) about 50\% and
RMSE approximately 1.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)}
\NormalTok{y }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{3}\NormalTok{, }\DecValTok{2}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{6}\NormalTok{, }\DecValTok{5}\NormalTok{, }\DecValTok{6}\NormalTok{)}
\NormalTok{Xy }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{y =}\NormalTok{ y)}

\NormalTok{mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}
\FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.4702829
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{sigma}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 1.094753
\end{verbatim}

Create a dataset \(\mathbb{D}\) which we call \texttt{Xy} such that the
linear model as \(R^2\) about 0\% but x, y are clearly associated.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{x }\OtherTok{=} \FunctionTok{c}\NormalTok{(}\DecValTok{1}\NormalTok{, }\DecValTok{3}\NormalTok{, }\DecValTok{4}\NormalTok{, }\DecValTok{7}\NormalTok{, }\DecValTok{8}\NormalTok{)}
\NormalTok{y }\OtherTok{=}\NormalTok{ x }\SpecialCharTok{\^{}} \DecValTok{19}
\NormalTok{Xy }\OtherTok{=} \FunctionTok{data.frame}\NormalTok{(}\AttributeTok{x =}\NormalTok{ x, }\AttributeTok{y =}\NormalTok{ y)}

\NormalTok{mod }\OtherTok{=} \FunctionTok{lm}\NormalTok{(y }\SpecialCharTok{\textasciitilde{}}\NormalTok{ x)}
\FunctionTok{summary}\NormalTok{(mod)}\SpecialCharTok{$}\NormalTok{r.squared}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 0.5019083
\end{verbatim}

Extra credit: create a dataset \(\mathbb{D}\) and a model that can give
you \(R^2\) arbitrarily close to 1 i.e.~approximately 1 - epsilon but
RMSE arbitrarily high i.e.~approximately M.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{epsilon }\OtherTok{=} \FloatTok{0.01}
\NormalTok{M }\OtherTok{=} \DecValTok{1000}
\CommentTok{\#TO{-}DO}
\end{Highlighting}
\end{Shaded}

Write a function \texttt{my\_ols} that takes in \texttt{X}, a matrix
with with p columns representing the feature measurements for each of
the n units, a vector of \(n\) responses \texttt{y} and returns a list
that contains the \texttt{b}, the \(p+1\)-sized column vector of OLS
coefficients, \texttt{yhat} (the vector of \(n\) predictions),
\texttt{e} (the vector of \(n\) residuals), \texttt{df} for degrees of
freedom of the model, \texttt{SSE}, \texttt{SST}, \texttt{MSE},
\texttt{RMSE} and \texttt{Rsq} (for the R-squared metric). Internally,
you cannot use \texttt{lm} or any other package; it must be done
manually. You should throw errors if the inputs are non-numeric or not
the same length. Or if \texttt{X} is not otherwise suitable. You should
also name the class of the return value \texttt{my\_ols} by using the
\texttt{class} function as a setter. No need to create ROxygen
documentation here.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{my\_ols }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(X, y)\{}
  
\NormalTok{  X\_1 }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(}\FunctionTok{cbind}\NormalTok{(}\DecValTok{1}\NormalTok{, X))}
\NormalTok{  n }\OtherTok{=} \FunctionTok{length}\NormalTok{(y)}
\NormalTok{  p }\OtherTok{=} \FunctionTok{ncol}\NormalTok{(X\_1)}
  
  \CommentTok{\#if (n != nrow(X))\{}
   \CommentTok{\# stop("The length of X and y must be the same.")}
  \CommentTok{\#\}}
  
  \CommentTok{\#if (class(X[,1]) != "numeric" \&\& class(X) != "integer" \&\& class(X) != "dbl")\{}
   \CommentTok{\# stop("The input must be numeric.")}
  \CommentTok{\#\}}
  
\NormalTok{  y\_bar }\OtherTok{=} \FunctionTok{sum}\NormalTok{(y)}\SpecialCharTok{/}\NormalTok{n}
  
\NormalTok{  b }\OtherTok{=} \FunctionTok{solve}\NormalTok{(}\FunctionTok{t}\NormalTok{(X\_1) }\SpecialCharTok{\%*\%}\NormalTok{ X\_1) }\SpecialCharTok{\%*\%} \FunctionTok{t}\NormalTok{(X\_1) }\SpecialCharTok{\%*\%}\NormalTok{ y }
\NormalTok{  y\_hat }\OtherTok{=}\NormalTok{ X\_1 }\SpecialCharTok{\%*\%}\NormalTok{ b}
\NormalTok{  e }\OtherTok{=}\NormalTok{ y }\SpecialCharTok{{-}}\NormalTok{ y\_hat}
\NormalTok{  df }\OtherTok{=}\NormalTok{ p }\SpecialCharTok{+} \DecValTok{1}
\NormalTok{  SSE }\OtherTok{=} \FunctionTok{t}\NormalTok{(e) }\SpecialCharTok{\%*\%}\NormalTok{ e}
\NormalTok{  SST }\OtherTok{=} \FunctionTok{t}\NormalTok{(y }\SpecialCharTok{{-}}\NormalTok{ y\_bar) }\SpecialCharTok{\%*\%}\NormalTok{ (y }\SpecialCharTok{{-}}\NormalTok{ y\_bar)}
\NormalTok{  MSE }\OtherTok{=}\NormalTok{ SSE }\SpecialCharTok{/}\NormalTok{ (n }\SpecialCharTok{{-}}\NormalTok{ df)}
\NormalTok{  RMSE }\OtherTok{=} \FunctionTok{sqrt}\NormalTok{(MSE)}
\NormalTok{  Rsq }\OtherTok{=} \DecValTok{1} \SpecialCharTok{{-}}\NormalTok{ (SSE }\SpecialCharTok{/}\NormalTok{ SST)}
    
\NormalTok{  model\_ols }\OtherTok{=} \FunctionTok{list}\NormalTok{(}\StringTok{"b"} \OtherTok{=}\NormalTok{ b, }\StringTok{"y\_hat"} \OtherTok{=}\NormalTok{ y\_hat, }\StringTok{"e"} \OtherTok{=}\NormalTok{ e, }\StringTok{"df"} \OtherTok{=}\NormalTok{ df, }\StringTok{"SSE"} \OtherTok{=}\NormalTok{ SSE, }\StringTok{"SST"} \OtherTok{=}\NormalTok{ SST, }\StringTok{"MSE"} \OtherTok{=}\NormalTok{ MSE, }\StringTok{"RMSE"} \OtherTok{=}\NormalTok{ RMSE, }\StringTok{"Rsq"} \OtherTok{=}\NormalTok{ Rsq)}
  \FunctionTok{class}\NormalTok{(model\_ols) }\OtherTok{=} \StringTok{"my\_ols\_obj"}
\NormalTok{  model\_ols}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

Verify that the OLS coefficients for the \texttt{Type} of cars in the
cars dataset gives you the same results as we did in class (i.e.~the
ybar's within group).

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{X }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(cars}\SpecialCharTok{$}\NormalTok{dist)}
\NormalTok{y }\OtherTok{=} \FunctionTok{as.matrix}\NormalTok{(cars}\SpecialCharTok{$}\NormalTok{speed)}

\FunctionTok{my\_ols}\NormalTok{(X, y)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $b
##           [,1]
## [1,] 8.2839056
## [2,] 0.1655676
## 
## $y_hat
##            [,1]
##  [1,]  8.615041
##  [2,]  9.939581
##  [3,]  8.946176
##  [4,] 11.926392
##  [5,] 10.932987
##  [6,]  9.939581
##  [7,] 11.264122
##  [8,] 12.588663
##  [9,] 13.913203
## [10,] 11.098554
## [11,] 12.919798
## [12,] 10.601852
## [13,] 11.595257
## [14,] 12.257527
## [15,] 12.919798
## [16,] 12.588663
## [17,] 13.913203
## [18,] 13.913203
## [19,] 15.900014
## [20,] 12.588663
## [21,] 14.244338
## [22,] 18.217960
## [23,] 21.529312
## [24,] 11.595257
## [25,] 12.588663
## [26,] 17.224555
## [27,] 13.582068
## [28,] 14.906609
## [29,] 13.582068
## [30,] 14.906609
## [31,] 16.562284
## [32,] 15.237744
## [33,] 17.555690
## [34,] 20.867041
## [35,] 22.191582
## [36,] 14.244338
## [37,] 15.900014
## [38,] 19.542501
## [39,] 13.582068
## [40,] 16.231149
## [41,] 16.893420
## [42,] 17.555690
## [43,] 18.880230
## [44,] 19.211366
## [45,] 17.224555
## [46,] 19.873636
## [47,] 23.516123
## [48,] 23.681690
## [49,] 28.152015
## [50,] 22.357149
## 
## $e
##              [,1]
##  [1,] -4.61504079
##  [2,] -5.93958139
##  [3,] -1.94617594
##  [4,] -4.92639228
##  [5,] -2.93298684
##  [6,] -0.93958139
##  [7,] -1.26412199
##  [8,] -2.58866258
##  [9,] -3.91320318
## [10,] -0.09855441
## [11,] -1.91979773
## [12,]  1.39814831
## [13,]  0.40474287
## [14,] -0.25752743
## [15,] -0.91979773
## [16,]  0.41133742
## [17,] -0.91320318
## [18,] -0.91320318
## [19,] -2.90001408
## [20,]  1.41133742
## [21,] -0.24433833
## [22,] -4.21796012
## [23,] -7.52931161
## [24,]  3.40474287
## [25,]  2.41133742
## [26,] -2.22455467
## [27,]  2.41793197
## [28,]  1.09339137
## [29,]  3.41793197
## [30,]  2.09339137
## [31,]  0.43771563
## [32,]  2.76225622
## [33,]  0.44431018
## [34,] -2.86704131
## [35,] -4.19158191
## [36,]  4.75566167
## [37,]  3.09998592
## [38,] -0.54250072
## [39,]  6.41793197
## [40,]  3.76885078
## [41,]  3.10658048
## [42,]  2.44431018
## [43,]  1.11976958
## [44,]  2.78863443
## [45,]  5.77544533
## [46,]  4.12636413
## [47,]  0.48387749
## [48,]  0.31830992
## [49,] -4.15201460
## [50,]  2.64285051
## 
## $df
## [1] 3
## 
## $SSE
##          [,1]
## [1,] 478.0212
## 
## $SST
##      [,1]
## [1,] 1370
## 
## $MSE
##          [,1]
## [1,] 10.17066
## 
## $RMSE
##          [,1]
## [1,] 3.189148
## 
## $Rsq
##           [,1]
## [1,] 0.6510794
## 
## attr(,"class")
## [1] "my_ols_obj"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{my\_simple\_ols}\NormalTok{(cars}\SpecialCharTok{$}\NormalTok{dist, cars}\SpecialCharTok{$}\NormalTok{speed)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## $b_0
## [1] 8.283906
## 
## $b_1
## [1] 0.1655676
## 
## $y_hat
##  [1]  8.615041  9.939581  8.946176 11.926392 10.932987  9.939581 11.264122
##  [8] 12.588663 13.913203 11.098554 12.919798 10.601852 11.595257 12.257527
## [15] 12.919798 12.588663 13.913203 13.913203 15.900014 12.588663 14.244338
## [22] 18.217960 21.529312 11.595257 12.588663 17.224555 13.582068 14.906609
## [29] 13.582068 14.906609 16.562284 15.237744 17.555690 20.867041 22.191582
## [36] 14.244338 15.900014 19.542501 13.582068 16.231149 16.893420 17.555690
## [43] 18.880230 19.211366 17.224555 19.873636 23.516123 23.681690 28.152015
## [50] 22.357149
## 
## $e
##  [1] -4.61504079 -5.93958139 -1.94617594 -4.92639228 -2.93298684 -0.93958139
##  [7] -1.26412199 -2.58866258 -3.91320318 -0.09855441 -1.91979773  1.39814831
## [13]  0.40474287 -0.25752743 -0.91979773  0.41133742 -0.91320318 -0.91320318
## [19] -2.90001408  1.41133742 -0.24433833 -4.21796012 -7.52931161  3.40474287
## [25]  2.41133742 -2.22455467  2.41793197  1.09339137  3.41793197  2.09339137
## [31]  0.43771563  2.76225622  0.44431018 -2.86704131 -4.19158191  4.75566167
## [37]  3.09998592 -0.54250072  6.41793197  3.76885078  3.10658048  2.44431018
## [43]  1.11976958  2.78863443  5.77544533  4.12636413  0.48387749  0.31830992
## [49] -4.15201460  2.64285051
## 
## $SSE
## [1] 478.0212
## 
## $SST
## [1] 1370
## 
## $MSE
## [1] 9.958776
## 
## $RMSE
## [1] 3.155753
## 
## $R_squared
## [1] 0.6510794
## 
## attr(,"class")
## [1] "my_simple_ols_obj"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{lm}\NormalTok{(speed }\SpecialCharTok{\textasciitilde{}}\NormalTok{ dist, cars)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## Call:
## lm(formula = speed ~ dist, data = cars)
## 
## Coefficients:
## (Intercept)         dist  
##      8.2839       0.1656
\end{verbatim}

Create a prediction method \texttt{g} that takes in a vector
\texttt{x\_star} and the dataset \(\mathbb{D}\) i.e.~\texttt{X} and
\texttt{y} and returns the OLS predictions. Let \texttt{X} be a matrix
with with p columns representing the feature measurements for each of
the n units

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\#n = 8}
\CommentTok{\#X = matrix(data = NA, nrow = n, ncol = length(y))}

\NormalTok{g }\OtherTok{=} \ControlFlowTok{function}\NormalTok{(x\_star, X, y)\{}
\NormalTok{  mod }\OtherTok{=} \FunctionTok{my\_ols}\NormalTok{(X,y)}
\NormalTok{  b }\OtherTok{=}\NormalTok{ mod}\SpecialCharTok{$}\NormalTok{b}
\NormalTok{  x\_star }\OtherTok{=} \FunctionTok{cbind}\NormalTok{(}\DecValTok{1}\NormalTok{, x\_star)}
\NormalTok{  y\_hat\_star }\OtherTok{=}\NormalTok{ x\_star }\SpecialCharTok{\%*\%}\NormalTok{ b}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}


\end{document}
